name: Vulnerability Audit & Lock Breaker

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  audit-and-fix:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v5
          
      - uses: actions/setup-node@v4
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        
      - name: Audit vulnerabilities
        id: audit
        run: |
          # Run audit and extract package names with vulnerabilities
          PACKAGES=$(yarn npm audit --json | jq -r '.vulnerabilities | keys[]' | sort -u | tr '\n' ' ')
          echo "packages=$PACKAGES" >> $GITHUB_OUTPUT
          echo "Found vulnerable packages: $PACKAGES"
          
      - name: Run Lock Breaker
        if: steps.audit.outputs.packages != ''
        uses: RateGravity/lock-breaker@v1
        with:
          packages: ${{ steps.audit.outputs.packages }}
          
      - name: Check for changes from main
        id: changes
        run: |
          if git diff --quiet main HEAD; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "🔒 Fix vulnerabilities found in audit"
          body: |
            ## Vulnerability Audit Results
            
            This PR addresses vulnerabilities found during the scheduled security audit.
            
            **Packages updated:**
            ${{ steps.audit.outputs.packages }}
            
            **Changes made:**
            - Ran lock breaker action to resolve dependency conflicts
            - Updated package locks to secure versions
            
            **Auto-generated by:** `vulnerability-audit` workflow
            **Triggered on:** ${{ github.event_name }}
          labels: |
            security
            dependencies
            automated
