name: Example - Manual Refresh Dependencies

# This is an example of manually refreshing specific packages
# For automated Dependabot vulnerability resolution, see dependabot-refresh.yml

on:
  workflow_dispatch:
    inputs:
      packages:
        description: 'Space-separated list of packages to refresh'
        required: true
        default: 'lodash moment'
      commit:
        description: 'Commit changes'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      create_pr:
        description: 'Create a pull request for the changes'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'

jobs:
  refresh-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Refresh packages in yarn.lock
        uses: ./  # Use this action from current repository
        id: refresh
        with:
          packages: ${{ github.event.inputs.packages }}
          commit: ${{ github.event.inputs.commit }}
          commit-message: 'chore: refresh ${{ github.event.inputs.packages }} dependencies'
      
      - name: Display results
        run: |
          echo "Updated packages: ${{ steps.refresh.outputs.updated-packages }}"
          echo "Commit SHA: ${{ steps.refresh.outputs.commit-sha }}"
      
      - name: Create Pull Request
        if: github.event.inputs.create_pr == 'true' && steps.refresh.outputs.commit-sha != ''
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: refresh-deps-${{ github.run_number }}
          title: 'chore: refresh ${{ github.event.inputs.packages }} dependencies'
          body: |
            ## 🔄 Dependency Refresh
            
            This PR refreshes the following packages in yarn.lock:
            - ${{ steps.refresh.outputs.updated-packages }}
            
            ### Changes made:
            - Removed old entries from yarn.lock
            - Reinstalled packages to get latest compatible versions
            - Updated lock file with fresh dependency tree
            
            ### Commit SHA:
            ${{ steps.refresh.outputs.commit-sha }}
            
            ---
            *Generated by Lock Breaker Action*
          labels: |
            dependencies
            automated
      
      - name: Push changes
        if: github.event.inputs.create_pr == 'false' && github.event.inputs.commit == 'true' && steps.refresh.outputs.commit-sha != ''
        run: |
          git push origin HEAD